"""add users table

Revision ID: 2dc42af60621
Revises: da2bfee24366
Create Date: 2026-04-04 23:40:13.928178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dc42af60621'
down_revision: Union[str, Sequence[str], None] = 'da2bfee24366'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.add_column('focus_sessions', sa.Column('user_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'focus_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('integration_accounts', sa.Column('user_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'integration_accounts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'integration_accounts', type_='foreignkey')
    op.drop_column('integration_accounts', 'user_id')
    op.drop_constraint(None, 'focus_sessions', type_='foreignkey')
    op.drop_column('focus_sessions', 'user_id')
    op.drop_table('users')
    # ### end Alembic commands ###
