"""add channel_id to notifications

Revision ID: 62c38721857d
Revises: 92080696a7df
Create Date: 2026-04-05 00:49:39.158462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62c38721857d'
down_revision: Union[str, Sequence[str], None] = '92080696a7df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('channel_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_notifications_channel_id'), 'notifications', ['channel_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_channel_id'), table_name='notifications')
    op.drop_column('notifications', 'channel_id')
    # ### end Alembic commands ###
